services:
  # ── PostgreSQL ──────────────────────────────────────────
  postgres:
    image: postgres:15
    container_name: mlops_postgres
    environment:
      POSTGRES_USER: mlops
      POSTGRES_PASSWORD: mlops123
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlops"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ── MLflow Tracking Server ───────────────────────────────
  mlflow:
    image: python:3.11-slim
    container_name: mlops_mlflow
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://mlops:mlops123@postgres:5432/mlops_db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
               mlflow server
               --backend-store-uri postgresql://mlops:mlops123@postgres:5432/mlops_db
               --default-artifact-root /mlflow/artifacts
               --host 0.0.0.0
               --port 5000"

  # ── Apache Airflow ───────────────────────────────────────
  airflow:
    image: apache/airflow:2.8.0
    container_name: mlops_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://mlops:mlops123@postgres:5432/mlops_db
      AIRFLOW__CORE__FERNET_KEY: "ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg="
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mlops_secret_key"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "airflow db init &&
               airflow users create
               --username admin
               --password admin
               --firstname Shefali
               --lastname Saini
               --role Admin
               --email shefalisaini2@gmail.com &&
               airflow webserver & airflow scheduler"

  # ── Grafana ──────────────────────────────────────────────
  grafana:
    image: grafana/grafana:10.2.0
    container_name: mlops_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  mlflow_artifacts:
  airflow_logs:
  grafana_data:
